### ISSUE TITLE
Data Directory dialog open file dialog instead of directory dialog

### ISSUE THREAD

**Issue by varshard** [ethereum/grid-ui#39]
Data Director dialog in Setting tab open file dialog instead of directory dialog, which only allow file selection instead of a directory.

Purposed solution
Add `webkitdirectory directory` to `<input type="file"/>`

**Comment by marcgarreau** [comment]
Good catch! Thanks for filing the issue and being one of our earliest testers 😎

**Comment by ryanio** [comment]
Thanks! PR incoming
