### ISSUE TITLE
bn.js included multiple times

### ISSUE THREAD

**Issue by PhilippLgh** [ethereum/grid-ui#4]
when we bundle the app with webpack `yarn build` && `yarn analyze` we see that bn.js is included multiple times as a dependency and bloats the updates.
maybe we can find a stable way to have it included only once:
![image](https://user-images.githubusercontent.com/4280481/49941169-06814800-fee2-11e8-9ade-17281119aeb9.png)

**Comment by ryanio** [comment]
This may be able to be solved with peerDependencies: 

> Normally, npm package dependencies are listed under a "dependencies" key in the package’s package.json file. There is, however, another, less-used key called "peerDependencies", which has the same format as the ordinary dependencies list. The difference shows up in how npm performs dependency resolution: rather than getting its own copy of a peer dependency, a package expects that dependency to be provided by its dependent.

https://lexi-lambda.github.io/blog/2016/08/24/understanding-the-npm-dependency-model/

**Comment by ryanio** [comment]
This may be useful: https://github.com/atlassian/yarn-deduplicate

I'm not sure how it's best used yet, but ideally it would be integrated in something like a `postinstall` script so it runs in the background after `yarn install` without any extra steps needed by the user.
